Repository katrina799/KittyKats, pull requests merged in 2024-06, with the labels that each got.

#10 7 - Create prep list page, create css for prep list
  src/index.html
  src/pages/prep-list.html
  src/static/css/prep-list-style.css
  src/static/images/Instagram_logo_2022.png
  src/static/images/fireball1.jpg
  src/static/images/snowball-want-to-eat.jpg
  src/static/images/snowball1.jpg
Labels: new feature

#11 9 - Add devcontainer
  .devcontainer/devcontainer.json
  src/requirements.txt
Labels: repo management

#12 6-Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, new feature

#14 8 - Add Flask initially, add settings to use black formatter on save in d…
  .devcontainer/devcontainer.json
  src/Flask-instructions.md
  src/app.py
  src/templates/fun-stories.html
  src/templates/index.html
  src/templates/polls.html
  src/templates/prep-list.html
  src/templates/structure.html
Labels: repo management, Backend, Flask
